language: java
sudo: false
script: mvn install
deploy:
  provider: releases
  api_key:
    secure: hIsUQQ1WVvOqaoM3ZaTNaqYsn6gleVI2QC8UUGXhb5Uhqb8pHv5YoDp9aRL0ml5qCnw8l9eyjOCdvAYbP8eRjWdhU4Qkm3vPaRgHSYMpTXhiFKrY0odl15FCHd4i/gLybZBku4TedazE8iKCNYtSgQjcustF+PiamlJyuyaBacXO1+9VthZ7XxRwcKCIqZGIgySX6U2w8zO12u1/0yxqFPT1rTvoMKoTD8FMbN/+rk99UMsy+nyueI6FiIxitPG0QXiNuUpYrBTIQBdXEZ24rVZmJfcLPMRoB574XM5gkza4Cp23AhnU1NhDldDNxKq8t61qJZAiBwq6vIwd+bjDCroI8qpVVdk6BOcn2oi5Fm2Y/vbQH7RXa9eaQVCga9TjlcVYXB5vcrgaGBxoRK4bkvshRnVONusZpKP3rcpF92BDBzA8p+n6sEG1sHie4yUS2cNyy4dMzapsB8QTj/zeitUEmI3NtxhBBC1WZt2xrjrmAKsbEIr6o3oml6ialr8x8NKfjVaXlw1PyHZWLS4QjrkujWG3yS07N5cdUb78CsEC/YkVIrP7t+wSOxdai4Asso1uWsiDRnRzr4i55Osf7xH/pJJmCCL2yF6rU9NAOdT0MDBb2w8dwe4LSeNCB6e3SaN0Z7ZoL2sQKbPpIfhyT4wCY6xUWeMxMrwkzFb+VPI=
  file: /home/travis/.m2/repository/ch/bbw/ConsoleCalculatorWithMaven/1.0-SNAPSHOT/ConsoleCalculatorWithMaven-1.0-SNAPSHOT.jar
  on:
    repo: jannikhug/ConsoleCalculatorWithMavenGit
